# Generated by Django 2.0.1 on 2019-03-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassToStudent_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.TextField(verbose_name='Class ID')),
                ('RollNo', models.TextField(verbose_name='Roll Number')),
            ],
        ),
        migrations.CreateModel(
            name='ClassToSub_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.TextField(verbose_name='Class ID')),
                ('Subject1', models.TextField(verbose_name='Subject-1')),
                ('Subject2', models.TextField(verbose_name='Subject-2')),
                ('Subject3', models.TextField(verbose_name='Subject-3')),
                ('Subject4', models.TextField(verbose_name='Subject-4')),
                ('Subject5', models.TextField(verbose_name='Subject-5')),
                ('Subject6', models.TextField(verbose_name='Subject-6')),
                ('Subject7', models.TextField(verbose_name='Subject-7')),
                ('Subject8', models.TextField(verbose_name='Subject-8')),
                ('Subject9', models.TextField(verbose_name='Subject-9')),
                ('Subject10', models.TextField(verbose_name='Subject-10')),
                ('Subject11', models.TextField(verbose_name='Subject-11')),
                ('Subject12', models.TextField(verbose_name='Subject-12')),
            ],
        ),
        migrations.CreateModel(
            name='CumulativeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.TextField(verbose_name='Roll Number')),
                ('Subject1', models.IntegerField(verbose_name='Subject-1')),
                ('Subject2', models.IntegerField(verbose_name='Subject-2')),
                ('Subject3', models.IntegerField(verbose_name='Subject-3')),
                ('Subject4', models.IntegerField(verbose_name='Subject-4')),
                ('Subject5', models.IntegerField(verbose_name='Subject-5')),
                ('Subject6', models.IntegerField(verbose_name='Subject-6')),
                ('Subject7', models.IntegerField(verbose_name='Subject-7')),
                ('Subject8', models.IntegerField(verbose_name='Subject-8')),
                ('Subject9', models.IntegerField(verbose_name='Subject-9')),
                ('Subject10', models.IntegerField(verbose_name='Subject-10')),
                ('Subject11', models.IntegerField(verbose_name='Subject-11')),
                ('Subject12', models.IntegerField(verbose_name='Subject-12')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.TextField(verbose_name='Roll Number')),
                ('Date_c', models.DateField(verbose_name='Date')),
                ('Subject1', models.IntegerField(verbose_name='Subject-1')),
                ('Subject2', models.IntegerField(verbose_name='Subject-2')),
                ('Subject3', models.IntegerField(verbose_name='Subject-3')),
                ('Subject4', models.IntegerField(verbose_name='Subject-4')),
                ('Subject5', models.IntegerField(verbose_name='Subject-5')),
                ('Subject6', models.IntegerField(verbose_name='Subject-6')),
                ('Subject7', models.IntegerField(verbose_name='Subject-7')),
                ('Subject8', models.IntegerField(verbose_name='Subject-8')),
                ('Subject9', models.IntegerField(verbose_name='Subject-9')),
                ('Subject10', models.IntegerField(verbose_name='Subject-10')),
                ('Subject11', models.IntegerField(verbose_name='Subject-11')),
                ('Subject12', models.IntegerField(verbose_name='Subject-12')),
            ],
        ),
        migrations.CreateModel(
            name='DidClassHappenOnDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.TextField(verbose_name='Class ID')),
                ('Date_c', models.DateField(verbose_name='Date')),
                ('Subject1', models.IntegerField(verbose_name='Subject-1')),
                ('Subject2', models.IntegerField(verbose_name='Subject-2')),
                ('Subject3', models.IntegerField(verbose_name='Subject-3')),
                ('Subject4', models.IntegerField(verbose_name='Subject-4')),
                ('Subject5', models.IntegerField(verbose_name='Subject-5')),
                ('Subject6', models.IntegerField(verbose_name='Subject-6')),
                ('Subject7', models.IntegerField(verbose_name='Subject-7')),
                ('Subject8', models.IntegerField(verbose_name='Subject-8')),
                ('Subject9', models.IntegerField(verbose_name='Subject-9')),
                ('Subject10', models.IntegerField(verbose_name='Subject-10')),
                ('Subject11', models.IntegerField(verbose_name='Subject-11')),
                ('Subject12', models.IntegerField(verbose_name='Subject-12')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('venue', models.CharField(max_length=120)),
                ('manager', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=None, max_length=6)),
                ('department', models.CharField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'EIE'), ('4', 'MECH'), ('5', 'CIV')], default=None, max_length=6)),
                ('section', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=None, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='profToSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.TextField(verbose_name='Roll No')),
                ('prof', models.TextField(verbose_name='Professor')),
                ('subId', models.IntegerField(verbose_name='Subject Id')),
            ],
        ),
        migrations.CreateModel(
            name='ProfToSub_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.TextField(verbose_name='Class ID')),
                ('Professor', models.TextField(verbose_name='Professor')),
                ('SubjectId', models.IntegerField(verbose_name='Subject Id')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quizzes',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
